#!/bin/sh
# tools/fixtures/geode_libraries_scan.sh -- the module index, read off the tree.
#
# WHY GENERATED. An index of what a tree contains is the fastest-rotting page a tree can own: every
# module added or renamed makes it a little less true, and nobody notices because an index is
# trusted rather than checked. So this one is read off disk each time and written between markers
# that say not to edit it by hand, the same discipline the README metrics block already keeps.
#
# WHAT COUNTS AS A LIBRARY. A top-level directory holding at least one `.rye` module AND its own
# README.md. Both halves matter: code without a README has no door a reader can open, and a README
# without code is a room rather than a library.
#
# USAGE
#   sh tools/fixtures/geode_libraries_scan.sh
#
# Driven by tools/g/geode_libraries.rish. Run from the repository root.

set -eu

# HOW THE WITNESSES ARE FOUND, and it is a `find` rather than a shell glob for a reason paid for
# once. Both counts here read `tools/*_witness.rish`, a glob that matched every witness while the
# room stood flat and matched NOTHING the moment `tools/` folded into letter rooms on
# `20260823.144100`. The page then regenerated with a witness count of zero for all thirty-eight
# rooms, and the freshness guard passed -- because the page and the fresh render were computed by
# the same broken glob and agreed perfectly (REDS %169). A recursive find carries no assumption
# about how deep the room is arranged.
witness_roster="$(mktemp)"
trap 'rm -f "$witness_roster"' EXIT
find tools -type f -name '*_witness.rish' 2>/dev/null | sort > "$witness_roster"

# A ROSTER OF ZERO IS A RED, NEVER A READING. Every count below is taken against this one list, so
# an empty list would hand back a confident zero for all thirty-eight rooms -- which is exactly
# what happened when the flat glob this replaced stopped matching (REDS %169). The refusal is what
# turns a silent wrong number into a stopped line.
if [ ! -s "$witness_roster" ]; then
  echo "refused: no witnesses found under tools/ -- the roster this page counts against is empty" >&2
  exit 1
fi

witness_count() {
  xargs -a "$witness_roster" -d '\n' grep -lI "\b$1/" 2>/dev/null | wc -l | tr -d ' '
}

verb="${1:-census}"

# render writes the whole page. The prose lives here rather than in the page, so there is exactly
# one source for it and a hand-edit of the page is simply overwritten on the next run -- which is
# the point: an index nobody regenerates is an index that quietly stops being true.
if [ "$verb" = render ]; then
  cat <<'HEAD'
# The Libraries

*Every room in this tree that holds Rye modules and opens a door to them -- counted off the tree itself, never typed.*

**Language:** EN - **Style:** Radiant - **Voice:** Kyri
**Status:** Living - **Kind:** crushed index, generated by `tools/g/geode_libraries.rish write`

---

**This page is generated.** Editing it by hand is not wrong so much as futile; the next run overwrites it. An index of what a tree contains is the fastest-rotting page a tree can own, because every module added makes it a little less true and nobody notices -- an index is trusted rather than checked. So this one is read off disk, and `tools/g/geode_libraries_witness.rish` reds when it drifts.

**What counts as a library here:** a top-level room holding at least one `.rye` module *and* its own `README.md`. Both halves matter -- code with no README has no door a reader can open, and a README with no code is a room rather than a library.

**How the witness count is taken:** a witness belongs to a room when it *references* that room, not when its filename happens to contain the room name. The obvious way -- globbing `tools/*<room>*_witness.rish` -- reported **zero** witnesses for `image` and for `lotus`, which between them hold 463 modules and 485 witnesses, because their proofs are named for what they prove rather than for where it lives. A confident wrong zero is worse than no number at all.

| Room | Rye modules | Witnesses that reference it |
|---|---:|---:|
HEAD
  for dir in */; do
    room="${dir%/}"
    case "$room" in .*|seed|vendor|gratitude|old) continue ;; esac
    [ -f "$room/README.md" ] || continue
    n=$(find "$room" -maxdepth 2 -name '*.rye' -type f 2>/dev/null | wc -l | tr -d ' ')
    [ "$n" -gt 0 ] || continue
    w=$(witness_count "$room")
    printf '| [`%s/`](../../%s/README.md) | %s | %s |
' "$room" "$room" "$n" "$w"
  done
  cat <<'TAIL'

---

*A library is a promise that someone can use what you built. May each room above keep its door open, and may this page stay true by being read rather than remembered.*
TAIL
  exit 0
fi

echo "generated_from=the tree itself"

count=0
for dir in */; do
  room="${dir%/}"
  case "$room" in .*|seed|vendor|gratitude|old) continue ;; esac
  [ -f "$room/README.md" ] || continue
  n=$(find "$room" -maxdepth 2 -name '*.rye' -type f 2>/dev/null | wc -l | tr -d ' ')
  [ "$n" -gt 0 ] || continue
  # A witness BELONGS to a room when it references that room, not when its filename happens to
  # contain the room name. The name-glob reported zero witnesses for `image` (225 modules) and
  # for `lotus` (238), because their witnesses are named for what they prove rather than for
  # where it lives -- and an index that reports a confident wrong zero is worse than one that
  # reports nothing at all.
  w=$(witness_count "$room")
  echo "lib=$room modules=$n witnesses=$w"
  count=$((count + 1))
done

echo "libraries=$count"
if [ "$count" -gt 0 ]; then echo "verdict=ok"; else echo "verdict=empty"; exit 1; fi
